[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip uninstall python-telegram-bot python-telegram-bot[job-queue] -y",
  "pip install python-telegram-bot[job-queue]==20.8 --no-cache-dir --force-reinstall"
]

[start]
cmd = "python main.py"
